### ISSUE TITLE
Use set rather than list for unordered collections

### ISSUE THREAD

**Issue by trickeydan** [j5api/j5#207]
I think a `Set` would be a more appropriate return type for this function.

_Originally posted by @kierdavis in https://github.com/j5api/j5/pull/195_

**Comment by kierdavis** [comment]
On second thoughts, a BoardGroup already has a defined order, so I think we should stick to a list for `BoardGroup.boards`.

However, there's still quite a few places where it would be better to use a set rather than a list e.g. `Backend.discover`, `Board.supported_components`. I'm going to repurpose this issue.

**Comment by trickeydan** [comment]
Related to #23

**Comment by kierdavis** [comment]
I have some WIP stuff for this, will open a PR soon.
