### ISSUE TITLE
Use Tuple[Component] on boards to prevent mutability issues.

### ISSUE THREAD

**Issue by tpoomlmly** [j5api/j5#549]
It's possible to do this:
`Robot().motor_board.motors[0] = 1` rendering the motor unusable.

**Comment by trickeydan** [comment]
This is a wider problem that stems from using `List[Motor]`, as `List` is mutable and therefore won't stop them from editing it.

As this is currently the syntax of the SR API, it is very important that we change this.

However, this is a breaking change due to the type change, therefore rescheduling it to `0.10.x`
